package gui;

import java.awt.Image;
import model.Producto;
import model.Chat;
import model.Usuario;
import model.Direccion;
import model.CuentaBancaria;
import file.CompraFile;
import javax.swing.*;

/**
 *
 * @author Alejandro David Sánchez Marrero
 */

public class CompraForm extends javax.swing.JFrame {
    
    public Producto producto;
    public Chat chat;
    public Usuario usuario;
    public Direccion direccion;
    public CuentaBancaria cuentaBancaria;
    public CompraFile file;
    
    /**
     * Creates new form compraForm
     */
    public CompraForm() {
        initComponents();
        setLocationRelativeTo(null); //Coloca en el centro de la pantalla la aplicación 
    }
    
    /**
     * Método que se encarga de limpiar varios campos de texto
     */
    public void limpiarTF() {
        TFnombreProducto.setText("");
        TAdescripcion.setText("");
        TFprecio.setText("");
        TFnombre.setText("");
        TFemail.setText("");
        TFnumTel.setText("");
        TFcalle.setText("");
        TFcPostal.setText("");
        TFciudad.setText("");
        TFnTarjeta.setText("");
        TFcSeguridad.setText("");
        TFfechaCaducidad.setText("");
        TFsaldo.setText("");
    }
    
    /**
     * Método que se encarga de mostrar en una lista los productos puestos en venta
     */
    void mostrarProductos() {
        ListaVenta.removeAll();
        for(int i = 0; i < producto.listaProducto.size(); i++) {
           ListaVenta.add(producto.listaProducto.get(i).getNombre() + "[" + producto.listaProducto.get(i).getPrecio() + " €]");
        }
    }
    
    /**
     * Método que se encarga de mostrar en una lista los detalles del producto puesto en venta
     * 
     * @param p: producto que contendrá los detalles del producto puesto en venta
     */
    void mostrarDetallesProductos(Producto p) {
        ListaDetallesProducto.removeAll();
        ListaDetallesProducto.add("Nombre del producto: " + p.getNombre());
        ListaDetallesProducto.add("Precio del producto: " + p.getPrecio() + " €");
        ListaDetallesProducto.add("Descripción del producto: " + p.getDescripcion());
        ListaDetallesProducto.add("¿El vendedor realiza envíos? " + p.envios());
        ListaDetallesProducto.add("El producto se encuentra: " + p.estadoProducto());
    }
    
    /**
     * Método encargado de mostrar en una lista los chats abiertos
     */
    void mostrarChat() {
        ListaChat.removeAll();
        for(int i = 0; i < chat.conver.size(); i++) {
            ListaChat.add(chat.conver.get(i).getNombreUsuarioInteresado());
        }
    }
    
    /**
     * Método encargado de mostrar en una lista los productos comprados
     */
    void mostrarComprados() {
        ListaComprados.removeAll();
        for(int i = 0; i < producto.productosComprados.size(); i++) {
            ListaComprados.add(producto.productosComprados.get(i));
        }
    }
        
    /**
     * Método que se encarga de buscar un número aleatorio de productos en el buscador de la página "Inicio"
     */
    void buscarVarios() {
        int n = (int) (Math.random() * 10); //Cabe la posibilidad de que sea 0
        if(n == 0) {
            ListaCoincidencias.add("No se ha encontrado el producto buscado...");
        } else {
            for(int i = 0; i < n; i++) {
                ListaCoincidencias.add(TFbuscar.getText() + "[" + Math.random() * 115 + "€]", i);
            }            
        }
    }
    
    /**
     * Método que se encarga rellenar los textos de áreas con los datos de perfil guardados del fichero
     * 
     * @param user: objeto con los datos del usuario a cargar
     * @param direccion: objeto con los datos de la direccion a cargar
     * @param cuentaBancaria : objeto con los datos de la cuenta bancaria a cargar
     */
    void mostrarPerfil(Usuario user, Direccion direccion, CuentaBancaria cuentaBancaria) {
        TAusuario.setText("Sus datos actuales son:\nNombre: " + user.getNombre() + "\nEmail: " + user.getEmail() + "\nNúmero de teléfono: " + user.getNumTel());
        TAdireccion.setText("Sus datos actuales son:\nCalle: " + direccion.getCalle() + "\nCódigo postal: " + direccion.getCPostal() + "\nCiudad: " + direccion.getCiudad());
        TAbancario.setText("Sus datos actuales son:\nNúmero de tarjeta: " + cuentaBancaria.getNTarjeta() + "\nCódigo de seguridad: " + cuentaBancaria.getCSeguridad() + "\nFecha de caducidad: " + cuentaBancaria.getFechaCaducidad() + "\nSaldo actual: " + cuentaBancaria.getDinero() +"€");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGaceptaEnvio = new javax.swing.ButtonGroup();
        BGestadoProducto = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pestañaInicio = new javax.swing.JInternalFrame();
        btnGuardarEstado = new javax.swing.JButton();
        btnCargarEstado = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        TFbuscar = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ListaCoincidencias = new java.awt.List();
        jLabel24 = new javax.swing.JLabel();
        ListaComprados = new java.awt.List();
        btnBuscar = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        pestañaChat = new javax.swing.JInternalFrame();
        btnEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TFmensaje = new javax.swing.JTextField();
        ListaChat = new java.awt.List();
        TFusuario = new javax.swing.JTextField();
        btnConversacion = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TAconversacion = new javax.swing.JTextArea();
        btnEliminarConver = new javax.swing.JButton();
        pestañaVentas = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        TFnombreProducto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TFprecio = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TAdescripcion = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        RBsiEnvio = new javax.swing.JRadioButton();
        RBnoEnvio = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        RBnuevo = new javax.swing.JRadioButton();
        RBusado = new javax.swing.JRadioButton();
        RBdesperfecto = new javax.swing.JRadioButton();
        btnVender = new javax.swing.JButton();
        ListaVenta = new java.awt.List();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ListaDetallesProducto = new java.awt.List();
        btnRetirar = new javax.swing.JButton();
        pestañaPerfil = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFnumTel = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAusuario = new javax.swing.JTextArea();
        TFnombre = new javax.swing.JTextField();
        TFemail = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TFnTarjeta = new javax.swing.JTextField();
        TFcSeguridad = new javax.swing.JTextField();
        TFfechaCaducidad = new javax.swing.JTextField();
        TFsaldo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TAbancario = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TFciudad = new javax.swing.JTextField();
        TFcalle = new javax.swing.JTextField();
        TFcPostal = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TAdireccion = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnCambiarFoto = new javax.swing.JButton();
        labelImagen = new javax.swing.JLabel();
        btnGuardarPerfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pestañaInicio.setTitle("Inicio");
        pestañaInicio.setVisible(true);

        btnGuardarEstado.setText("Guardar estado");
        btnGuardarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEstadoActionPerformed(evt);
            }
        });

        btnCargarEstado.setText("Cargar estado");
        btnCargarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarEstadoActionPerformed(evt);
            }
        });

        jLabel22.setText("¿Qué artículo estás buscando?");

        jLabel23.setText("Coincidencias:");

        jLabel24.setText("Mis compras");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pestañaInicioLayout = new javax.swing.GroupLayout(pestañaInicio.getContentPane());
        pestañaInicio.getContentPane().setLayout(pestañaInicioLayout);
        pestañaInicioLayout.setHorizontalGroup(
            pestañaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestañaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pestañaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestañaInicioLayout.createSequentialGroup()
                        .addGroup(pestañaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pestañaInicioLayout.createSequentialGroup()
                                .addGroup(pestañaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23))
                                .addGap(184, 276, Short.MAX_VALUE))
                            .addGroup(pestañaInicioLayout.createSequentialGroup()
                                .addComponent(ListaCoincidencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(pestañaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pestañaInicioLayout.createSequentialGroup()
                                .addComponent(ListaComprados, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(pestañaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCargarEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGuardarEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                            .addComponent(jLabel24)))
                    .addGroup(pestañaInicioLayout.createSequentialGroup()
                        .addComponent(TFbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pestañaInicioLayout.setVerticalGroup(
            pestañaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pestañaInicioLayout.createSequentialGroup()
                .addGroup(pestañaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestañaInicioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pestañaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(pestañaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGroup(pestañaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pestañaInicioLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(pestañaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ListaCoincidencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ListaComprados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pestañaInicioLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pestañaInicioLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnGuardarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnCargarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 178, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Inicio", pestañaInicio);

        pestañaChat.setTitle("Mostrar chat");
        pestañaChat.setVisible(true);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        jLabel1.setText("Chats");

        TFmensaje.setToolTipText("");

        ListaChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaChatActionPerformed(evt);
            }
        });

        btnConversacion.setText("Iniciar conversación");
        btnConversacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConversacionActionPerformed(evt);
            }
        });

        TAconversacion.setEditable(false);
        TAconversacion.setColumns(20);
        TAconversacion.setRows(5);
        jScrollPane2.setViewportView(TAconversacion);

        btnEliminarConver.setText("Eliminar conversación");
        btnEliminarConver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarConverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pestañaChatLayout = new javax.swing.GroupLayout(pestañaChat.getContentPane());
        pestañaChat.getContentPane().setLayout(pestañaChatLayout);
        pestañaChatLayout.setHorizontalGroup(
            pestañaChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestañaChatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pestañaChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ListaChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFusuario)
                    .addComponent(btnConversacion, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarConver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(pestañaChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre)
                    .addGroup(pestañaChatLayout.createSequentialGroup()
                        .addComponent(TFmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        pestañaChatLayout.setVerticalGroup(
            pestañaChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestañaChatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pestañaChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pestañaChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(ListaChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pestañaChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pestañaChatLayout.createSequentialGroup()
                        .addComponent(TFusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConversacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarConver))
                    .addGroup(pestañaChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                        .addComponent(TFmensaje)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mostrar chat", pestañaChat);

        pestañaVentas.setTitle("Subir producto");
        pestañaVentas.setToolTipText("");
        pestañaVentas.setVisible(true);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de tu producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel16.setText("¿Qué estás vendiendo?");

        jLabel17.setText("Precio");

        jLabel18.setText("Descripción");

        TAdescripcion.setColumns(20);
        TAdescripcion.setRows(5);
        jScrollPane5.setViewportView(TAdescripcion);

        jLabel19.setText("¿Haces envíos?");

        BGaceptaEnvio.add(RBsiEnvio);
        RBsiEnvio.setText("Sí");

        BGaceptaEnvio.add(RBnoEnvio);
        RBnoEnvio.setText("No");

        jLabel21.setText("¿En qué estado se encuentra el producto?");

        BGestadoProducto.add(RBnuevo);
        RBnuevo.setText("Nuevo");

        BGestadoProducto.add(RBusado);
        RBusado.setText("Usado");

        BGestadoProducto.add(RBdesperfecto);
        RBdesperfecto.setText("Con desperfectos");

        btnVender.setText("Vender producto");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFnombreProducto)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(TFprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(RBsiEnvio)
                                .addGap(18, 18, 18)
                                .addComponent(RBnoEnvio))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(9, 9, 9)))
                        .addGap(5, 5, 5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(RBnuevo)
                                .addGap(18, 18, 18)
                                .addComponent(RBusado)
                                .addGap(18, 18, 18)
                                .addComponent(RBdesperfecto)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVender)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFnombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBsiEnvio)
                    .addComponent(RBnoEnvio))
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBnuevo)
                            .addComponent(RBusado)
                            .addComponent(RBdesperfecto))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnVender, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap())
        );

        ListaVenta.setName(""); // NOI18N
        ListaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaVentaActionPerformed(evt);
            }
        });

        jLabel12.setText("Mis productos en venta");

        jLabel20.setText("Detalles del producto");

        btnRetirar.setText("Retirar producto");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pestañaVentasLayout = new javax.swing.GroupLayout(pestañaVentas.getContentPane());
        pestañaVentas.getContentPane().setLayout(pestañaVentasLayout);
        pestañaVentasLayout.setHorizontalGroup(
            pestañaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestañaVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pestañaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRetirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pestañaVentasLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addComponent(ListaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(pestañaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestañaVentasLayout.createSequentialGroup()
                        .addComponent(ListaDetallesProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pestañaVentasLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 266, Short.MAX_VALUE))))
        );
        pestañaVentasLayout.setVerticalGroup(
            pestañaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestañaVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pestañaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pestañaVentasLayout.createSequentialGroup()
                        .addGroup(pestañaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pestañaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ListaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ListaDetallesProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Subir producto", pestañaVentas);

        pestañaPerfil.setTitle("Mostrar perfil");
        pestañaPerfil.setVisible(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos públicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setText("Nombre:");

        jLabel3.setText("Email: ");

        jLabel4.setText("Número de teléfono: ");

        jLabel13.setText("Detalles de usuario");

        TAusuario.setEditable(false);
        TAusuario.setColumns(20);
        TAusuario.setRows(5);
        jScrollPane1.setViewportView(TAusuario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFnumTel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFnombre)
                            .addComponent(TFemail))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TFemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TFnumTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos bancarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel8.setText("Número de tarjeta: ");

        jLabel9.setText("Código de seguridad: ");

        jLabel10.setText("Fecha de caducidad: ");

        jLabel11.setText("Saldo disponible: ");

        jLabel15.setText("Detalles bancarios");

        TAbancario.setEditable(false);
        TAbancario.setColumns(20);
        TAbancario.setRows(5);
        jScrollPane4.setViewportView(TAbancario);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFnTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(TFfechaCaducidad)
                    .addComponent(TFsaldo)
                    .addComponent(TFcSeguridad, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TFnTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TFcSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TFfechaCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TFsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel5.setText("Ciudad: ");

        jLabel6.setText("Calle: ");

        jLabel7.setText("Código postal: ");

        TAdireccion.setEditable(false);
        TAdireccion.setColumns(20);
        TAdireccion.setRows(5);
        jScrollPane3.setViewportView(TAdireccion);

        jLabel14.setText("Detalles de dirección");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(TFcalle, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFcPostal))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFciudad)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TFcalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TFcPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TFciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imagen de perfil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnCambiarFoto.setText("Cambiar foto");
        btnCambiarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 109, Short.MAX_VALUE)
                        .addComponent(btnCambiarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCambiarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnGuardarPerfil.setText("Guardar datos");
        btnGuardarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pestañaPerfilLayout = new javax.swing.GroupLayout(pestañaPerfil.getContentPane());
        pestañaPerfil.getContentPane().setLayout(pestañaPerfilLayout);
        pestañaPerfilLayout.setHorizontalGroup(
            pestañaPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pestañaPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pestañaPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pestañaPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pestañaPerfilLayout.setVerticalGroup(
            pestañaPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestañaPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pestañaPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pestañaPerfilLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pestañaPerfilLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mostrar perfil", pestañaPerfil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * ACCIÓN DEL BOTÓN "ENVIAR" PARA LAS CONVERSACIONES
     */
    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed

        chat.conver.get(ListaChat.getSelectedIndex()).setMensaje(TAconversacion.getText() + TFmensaje.getText() + "\n");
        TAconversacion.setText(chat.conver.get(ListaChat.getSelectedIndex()).getMensaje());
        TFmensaje.setText("");
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * ACCIÓN DEL BOTÓN "GUARDAR DATOS" PARA LA MODIFICACIÓN DEL PERFIL
     */
    private void btnGuardarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPerfilActionPerformed
        
        if("".equals(TFnombre.getText()) || "".equals(TFemail.getText()) || "".equals(TFnumTel.getText()) || "".equals(TFciudad.getText()) ||  "".equals(TFcalle.getText()) || "".equals(TFcPostal.getText()) || "".equals(TFnTarjeta.getText()) || "".equals(TFcSeguridad.getText()) || "".equals(TFsaldo.getText()) || "".equals(TFfechaCaducidad.getText())) {
            TAusuario.setText("Datos erróneos");
            TAdireccion.setText("Datos erróneos");
            TAbancario.setText("Datos erróneos");
        } else {
            usuario = new Usuario(TFnombre.getText(), TFemail.getText(), TFnumTel.getText());
            direccion = new Direccion(TFcalle.getText(), TFcPostal.getText(), TFciudad.getText());
            cuentaBancaria = new CuentaBancaria(Integer.parseInt(TFnTarjeta.getText()), Integer.parseInt(TFcSeguridad.getText()), TFfechaCaducidad.getText(), Double.parseDouble(TFsaldo.getText()));
            
                    
            TAusuario.setText("Sus datos actuales son:\nNombre: " + usuario.getNombre() + "\nEmail: " + usuario.getEmail() + "\nNúmero de teléfono: " + usuario.getNumTel());
        
            TAdireccion.setText("Su dirección consta como:\nCalle: " + direccion.getCalle() + "\nCódigo postal: " + direccion.getCPostal() + "\nCiudad: " + direccion.getCiudad());
            
            TAbancario.setText("Sus datos bancarios son:\nNúmero de tarjeta: " + cuentaBancaria.getNTarjeta() + "\nCódigo de seguridad: " + cuentaBancaria.getCSeguridad() + "\nFecha de caducidad: " + cuentaBancaria.getFechaCaducidad()+ "\nSaldo actual: " + cuentaBancaria.getDinero() +" €");
            
            limpiarTF();
        }
    }//GEN-LAST:event_btnGuardarPerfilActionPerformed

    /**
     * ACCIÓN DEL BOTÓN "VENDER PRODUCTO" PARA SUBIR UN PRODUCTO
     */
    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        
        if(RBsiEnvio.isSelected()) {
            if(RBnuevo.isSelected()) {
                producto.añadirProducto(TFnombreProducto.getText(), Double.parseDouble(TFprecio.getText()), TAdescripcion.getText(), true, 0);
            } else if(RBusado.isSelected()) {
                producto.añadirProducto(TFnombreProducto.getText(), Double.parseDouble(TFprecio.getText()), TAdescripcion.getText(), true, 1);
            } else if(RBdesperfecto.isSelected()) {
                producto.añadirProducto(TFnombreProducto.getText(), Double.parseDouble(TFprecio.getText()), TAdescripcion.getText(), true, 2);
            }
        } else if(RBnoEnvio.isSelected()){
            if(RBnuevo.isSelected()) {
                producto.añadirProducto(TFnombreProducto.getText(), Double.parseDouble(TFprecio.getText()), TAdescripcion.getText(), false, 0);
            } else if(RBusado.isSelected()) {
                producto.añadirProducto(TFnombreProducto.getText(), Double.parseDouble(TFprecio.getText()), TAdescripcion.getText(), false, 1);
            } else if(RBdesperfecto.isSelected()) {
                producto.añadirProducto(TFnombreProducto.getText(), Double.parseDouble(TFprecio.getText()), TAdescripcion.getText(), false, 2);
            }
        }
        
        mostrarProductos();
        limpiarTF();
    }//GEN-LAST:event_btnVenderActionPerformed

    /**
     * CAMPO DE TEXTO DONDE SE MOSTRARÁ MÁS DETALLADAMENTE LOS PRODUCTOS PUESTOS EN VENTA
     */
    private void ListaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaVentaActionPerformed

        mostrarDetallesProductos(producto.listaProducto.get(ListaVenta.getSelectedIndex()));
    }//GEN-LAST:event_ListaVentaActionPerformed

    /**
     * ACCIÓN DEL BOTÓN "INCIAR CONVERSACIÓN" QUE AÑADIRÁ AL CHAT UN USUARIO CON EL QUE HABLAR
     */
    private void btnConversacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConversacionActionPerformed
        
        chat.añadirConver(TFmensaje.getText(), TFusuario.getText());
        mostrarChat();
        TFusuario.setText("");
    }//GEN-LAST:event_btnConversacionActionPerformed

    /**
     * LISTA CON TODOS LOS CHAT QUE HEMOS ABIERTO
     */
    private void ListaChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaChatActionPerformed
        
        lblNombre.setText(chat.conver.get(ListaChat.getSelectedIndex()).getNombreUsuarioInteresado());
        TAconversacion.setText(chat.conver.get(ListaChat.getSelectedIndex()).getMensaje());
    }//GEN-LAST:event_ListaChatActionPerformed

    /**
     * ACCIÓN DEL BOTÓN "RETIRAR PRODUCTO" QUE SE ENCARGA DE ELIMINAR LOS PRODUCTOS SELECCIONADOS PUESTOS EN VENTA
     */
    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        
        producto.eliminarProducto(producto.listaProducto.get(ListaVenta.getSelectedIndex()));
        ListaVenta.remove(ListaVenta.getSelectedIndex());
        ListaDetallesProducto.removeAll();
    }//GEN-LAST:event_btnRetirarActionPerformed

    /**
     * ACCIÓN DEL BOTÓN "BUSCAR" QUE SE ENCARGARÁ DE ENCONTRAR EL PRODUCTO QUE DESEEMOS
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        ListaCoincidencias.removeAll();
        buscarVarios();
        TFbuscar.setText("");
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * ACCIÓN DEL BOTÓN "COMPRAR" QUE ADQUIERE A TU LISTA DE PRODUCTOS COMPRADOS EL ELEMENTO DE "LISTACOINCIDENCIAS" SELECCIONADO
     */
    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        
        producto.comprarProducto(ListaCoincidencias.getSelectedItem());
        mostrarComprados();
    }//GEN-LAST:event_btnComprarActionPerformed

    /**
     * ACCIÓN DEL BOTÓN "CAMBIAR FOTO" PARA MODIFICAR LA FOTO DEL PERFIL
     */
    private void btnCambiarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarFotoActionPerformed
        
        JFileChooser fichero = new JFileChooser();
        if(fichero.showOpenDialog(CompraForm.this) == JFileChooser.APPROVE_OPTION) {
            ImageIcon image = new ImageIcon(fichero.getSelectedFile().getAbsolutePath());
            Icon icono = new ImageIcon(image.getImage().getScaledInstance(labelImagen.getWidth(), labelImagen.getHeight(), Image.SCALE_DEFAULT));
            labelImagen.setIcon(icono);
            this.repaint();
        }
    }//GEN-LAST:event_btnCambiarFotoActionPerformed

    /**
     * ACCIÓN DEL BOTÓN "GUARDAR ESTADO" QUE GUARDARÁ TODOS LOS DATOS INTRODUCIDOS
     */
    private void btnGuardarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEstadoActionPerformed
        //
        file.SaveToFile(chat, producto, usuario, direccion, cuentaBancaria);
    }//GEN-LAST:event_btnGuardarEstadoActionPerformed

    /**
     * ACCIÓN DEL BOTÓN "CARGAR ESTADO" QUE CARGARÁ TODOS LOS DATOS GUARDADOS
     */
    private void btnCargarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarEstadoActionPerformed
        
        file.loadFromFile(chat, producto);
        mostrarComprados();
        mostrarChat();
        mostrarProductos();
        usuario = file.getUsuario();
        direccion = file.getDireccion();
        cuentaBancaria = file.getCuenta();
        mostrarPerfil(usuario, direccion , cuentaBancaria);
    }//GEN-LAST:event_btnCargarEstadoActionPerformed

    /**
     * ACCIÓN DEL BOTÓN "ELIMINAR CONVERSACIÓN"
     */
    private void btnEliminarConverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarConverActionPerformed
        
        chat.eliminarConver(chat.conver.get(ListaChat.getSelectedIndex()));
        ListaChat.remove(ListaChat.getSelectedIndex());
        TAconversacion.setText("");
        lblNombre.setText("");
    }//GEN-LAST:event_btnEliminarConverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGaceptaEnvio;
    private javax.swing.ButtonGroup BGestadoProducto;
    private java.awt.List ListaChat;
    private java.awt.List ListaCoincidencias;
    private java.awt.List ListaComprados;
    private java.awt.List ListaDetallesProducto;
    private java.awt.List ListaVenta;
    private javax.swing.JRadioButton RBdesperfecto;
    private javax.swing.JRadioButton RBnoEnvio;
    private javax.swing.JRadioButton RBnuevo;
    private javax.swing.JRadioButton RBsiEnvio;
    private javax.swing.JRadioButton RBusado;
    private javax.swing.JTextArea TAbancario;
    private javax.swing.JTextArea TAconversacion;
    private javax.swing.JTextArea TAdescripcion;
    private javax.swing.JTextArea TAdireccion;
    private javax.swing.JTextArea TAusuario;
    private javax.swing.JTextField TFbuscar;
    private javax.swing.JTextField TFcPostal;
    private javax.swing.JTextField TFcSeguridad;
    private javax.swing.JTextField TFcalle;
    private javax.swing.JTextField TFciudad;
    private javax.swing.JTextField TFemail;
    private javax.swing.JTextField TFfechaCaducidad;
    private javax.swing.JTextField TFmensaje;
    private javax.swing.JTextField TFnTarjeta;
    private javax.swing.JTextField TFnombre;
    private javax.swing.JTextField TFnombreProducto;
    private javax.swing.JTextField TFnumTel;
    private javax.swing.JTextField TFprecio;
    private javax.swing.JTextField TFsaldo;
    private javax.swing.JTextField TFusuario;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCambiarFoto;
    private javax.swing.JButton btnCargarEstado;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnConversacion;
    private javax.swing.JButton btnEliminarConver;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnGuardarEstado;
    private javax.swing.JButton btnGuardarPerfil;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnVender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JInternalFrame pestañaChat;
    private javax.swing.JInternalFrame pestañaInicio;
    private javax.swing.JInternalFrame pestañaPerfil;
    private javax.swing.JInternalFrame pestañaVentas;
    // End of variables declaration//GEN-END:variables

}
